#!/usr/bin/env node
/**
 * DocuSign Click Agent Setup Script
 * Helps configure the environment for the first time
 */

import readline from 'readline';
import fs from 'fs/promises';
import path from 'path';

const rl = readline.createInterface({
  input: process.stdin,
  output: process.stdout
});

const question = (prompt) => new Promise(resolve => rl.question(prompt, resolve));

async function setup() {
  console.log();
  console.log('╔═══════════════════════════════════════════════════════════╗');
  console.log('║       DocuSign Click Agent - Initial Setup                ║');
  console.log('╚═══════════════════════════════════════════════════════════╝');
  console.log();
  console.log('This wizard will help you configure your DocuSign credentials.');
  console.log();
  console.log('BEFORE YOU BEGIN, you will need:');
  console.log('  1. A DocuSign Developer Account (free at developers.docusign.com)');
  console.log('  2. Your Account ID (from Apps and Keys page)');
  console.log('  3. An Access Token (from the Developer Tools)');
  console.log();

  const ready = await question('Do you have these ready? (y/n): ');

  if (ready.toLowerCase() !== 'y') {
    console.log();
    console.log('No problem! Here\'s how to get set up:');
    console.log();
    console.log('STEP 1: Create a DocuSign Developer Account');
    console.log('  - Go to: https://developers.docusign.com/');
    console.log('  - Click "Get Started Free"');
    console.log('  - Create your account with: jared@veldheerlinemanvault.com');
    console.log();
    console.log('STEP 2: Get Your Account ID');
    console.log('  - Log in to DocuSign Admin: https://admindemo.docusign.com/');
    console.log('  - Go to: Settings > Apps and Keys');
    console.log('  - Copy the "API Account ID" (a GUID like: xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx)');
    console.log();
    console.log('STEP 3: Generate an Access Token');
    console.log('  - Go to: https://developers.docusign.com/tools/api-access-token');
    console.log('  - Select "Click" as the API');
    console.log('  - Click "GET ACCESS TOKEN"');
    console.log('  - Copy the token');
    console.log();
    console.log('STEP 4: Run this setup again');
    console.log('  - Run: npm run setup');
    console.log();
    rl.close();
    return;
  }

  console.log();
  console.log('Great! Let\'s configure your environment.');
  console.log();

  // Get Account ID
  const accountId = await question('Enter your DocuSign Account ID (API Account ID): ');

  if (!accountId.trim()) {
    console.log('Account ID is required. Please run setup again.');
    rl.close();
    return;
  }

  // Get Access Token
  console.log();
  console.log('For the access token, you can get one from:');
  console.log('https://developers.docusign.com/tools/api-access-token');
  console.log();
  const accessToken = await question('Enter your Access Token: ');

  if (!accessToken.trim()) {
    console.log('Access Token is required. Please run setup again.');
    rl.close();
    return;
  }

  // Get Environment
  console.log();
  const envChoice = await question('Environment (demo/production) [demo]: ');
  const env = envChoice.trim().toLowerCase() === 'production' ? 'production' : 'demo';

  // Create .env file
  const envContent = `# DocuSign Configuration
# Generated by setup script on ${new Date().toISOString()}

# DocuSign Account Settings
DOCUSIGN_ACCOUNT_ID=${accountId.trim()}

# Access Token (expires in ~8 hours, regenerate when needed)
DOCUSIGN_ACCESS_TOKEN=${accessToken.trim()}

# Environment: 'demo' or 'production'
DOCUSIGN_ENV=${env}

# Note: For production use, set up JWT authentication
# See docs/jwt-setup.md for instructions
`;

  const envPath = path.join(process.cwd(), '.env');

  // Check if .env already exists
  try {
    await fs.access(envPath);
    const overwrite = await question('\n.env file already exists. Overwrite? (y/n): ');
    if (overwrite.toLowerCase() !== 'y') {
      console.log('Setup cancelled. Your existing .env file was not modified.');
      rl.close();
      return;
    }
  } catch {
    // File doesn't exist, we can create it
  }

  await fs.writeFile(envPath, envContent);

  console.log();
  console.log('='.repeat(50));
  console.log('Setup Complete!');
  console.log('='.repeat(50));
  console.log();
  console.log('Your .env file has been created with your credentials.');
  console.log();
  console.log('NEXT STEPS:');
  console.log('  1. Generate the PDF: npm run generate-pdf');
  console.log('  2. Create clickwrap: npm run create-clickwrap');
  console.log('  3. Or use the agent: npm start');
  console.log();
  console.log('IMPORTANT NOTES:');
  console.log('  - Access tokens expire after ~8 hours');
  console.log('  - Regenerate your token when it expires');
  console.log('  - Never commit your .env file to git');
  console.log();

  rl.close();
}

setup().catch(error => {
  console.error('Setup error:', error.message);
  process.exit(1);
});
